version: "3.5"

services:
  api01: &api
    image: ricardovhz/rinha2/api
    hostname: api01
    environment:
      - DEBUG=false
      - PORT=3000
      - STORE_HOST=store:5001
      - TCP_POOL_SIZE=100
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - rinha2
    ports:
      - "3001:3000"
    depends_on:
      - store
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"
  api02:
    <<: *api
    hostname: api02
    ports:

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: rinhaproxy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - rinha2
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '250MB'

  store:
    image: ricardovhz/rinha2/store
    hostname: store
    ports:
      - "5001:5001"
    environment:
      - STORE_CONN_TYPE=tcp
      - STORE_HOST=:5001
      - PATH_PREFIX=/data/store
    networks:
      - rinha2
    volumes:
      - store-data:/data/store/
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100MB"

networks:
  rinha2:

volumes:
  store-data:
