FROM golang:alpine3.18 AS build

# Important:
#   Because this is a CGO enabled package, you are required to set it as 1.
#ENV CGO_ENABLED=1

RUN apk add --no-cache \
    # Important: required for go-sqlite3
    #gcc \
    # Required for Alpine
    musl-dev

WORKDIR /workspace

COPY . /workspace/

RUN \
    go mod tidy && \
    cd cmd/store && \
    go install #-ldflags='-s -w -extldflags "-static"'

# -------------------
FROM scratch
COPY --from=build /go/bin/store /opt/app/
EXPOSE 5001
ENTRYPOINT ["/opt/app/store"]
